<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="com_z" value="${base_height/2.0}"/>

    <link name ="base_footprint" />
    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.6 0.4 0.2" />
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="0.6 0.4 0.2" />
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="0.6" y="0.4" z="0.2" o_xyz="0 0 0.1" o_rpy="0 0 0" />
    </link>

   
    <link name="right_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="gray" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="0.1" l="0.05"  o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>
    
    <link name="left_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="gray" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="0.1" l="0.05" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="gray" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="0.05" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>



    <!--LIDAR LINK-->
    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi} 0 0" />
            <material name="gray" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="0.1" l="0.1" o_xyz="0 0 0" o_rpy="${pi} 0 0" />
    </link>

    <!--IMU LINK-->
    
    <link name="imu_link">
      <visual>
         <geometry>
            <box size="0.1 0.1 0.1"/>
         </geometry>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <material name="gray"/>
      </visual>

      <collision>
          <geometry>
             <box size="0.1 0.1 0.1"/>
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>

      <inertial>
         <mass value="0.1"/>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <inertia ixx="0.00033" iyy="0.00033" izz="0.00033" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
       <parent link="base_link"/>
       <child link="imu_link"/>
       <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint>

    <!--CAMERA LINK-->
    <link name="camera_link">
         <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.130 0.022"/>
            </geometry>
         </visual>

         <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.130 0.022"/>
            </geometry>
         </collision>

         <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.035"/>
            <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
         </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.3 0 0.1" rpy="0 0 0"/>
    </joint>

    <link name="camera_depth_frame"/>

    <joint name="camera_depth_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
         <parent link="camera_link"/>
         <child link="camera_depth_frame"/>
    </joint>
    
   

    <joint name = "base_joint" type ="fixed">
        <parent link="base_footprint" />
        <child link = "base_link" />
        <origin xyz = "0 0 0.1" rpy ="0 0 0" />
    </joint>



    
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-0.15 -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-0.15 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0.15 0 0.225" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>



    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="0.2 0 -0.05" rpy="0 0 0" />
    </joint>




    
   

</robot>